name: "python-tests: non-WSL steps"
description: "Reusable non-WSL steps for tests: setup-python, install deps, lint, test and conditional coverage upload."
inputs:
  python-version:
    description: "Python version to use (e.g. 3.11)"
    required: true
  os:
    description: "OS name from the matrix (e.g. ubuntu-latest) - used for conditional uploads"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python (non-WSL)
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies (non-WSL)
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e .
        pip install -r requirements-dev.txt

    - name: Lint (non-WSL)
      shell: bash
      run: |
        flake8 src/gitspaces --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/gitspaces --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check code formatting with black (non-WSL)
      shell: bash
      run: |
        black --check src/gitspaces tests

    - name: Run tests (non-WSL)
      shell: bash
      run: |
        pytest tests/ -v --cov=src/gitspaces --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov (non-WSL)
      if: ${{ inputs.os == 'ubuntu-latest' && inputs.python-version == '3.11' }}
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
