name: "setup-venv"
description: "Set up a Python virtual environment with cross-platform support (Unix/macOS, Windows cmd/pwsh, WSL)"

inputs:
  python-version:
    description: "Python version to use (e.g. '3.13')"
    required: true
  venv-path:
    description: "Path for the virtual environment (default: .venv)"
    required: false
    default: ".venv"
  requirements-file:
    description: "Requirements file to install (optional)"
    required: false
    default: ""
  shell-type:
    description: "Shell type to use: bash | cmd | pwsh | wsl (auto-detected if not specified)"
    required: false
    default: ""
  cache-key-prefix:
    description: "Prefix for pip cache key (default: venv)"
    required: false
    default: "venv"

outputs:
  venv-path:
    description: "Path to the created virtual environment"
    value: ${{ steps.setup-unix.outputs.venv-path || steps.setup-win-cmd.outputs.venv-path || steps.setup-win-pwsh.outputs.venv-path || steps.setup-win-wsl.outputs.venv-path }}
  python-path:
    description: "Path to the Python executable in the venv"
    value: ${{ steps.setup-unix.outputs.python-path || steps.setup-win-cmd.outputs.python-path || steps.setup-win-pwsh.outputs.python-path || steps.setup-win-wsl.outputs.python-path }}

runs:
  using: "composite"
  steps:
    # Setup Python - only for non-WSL (WSL uses system Python from Ubuntu)
    - name: Setup Python
      if: inputs.shell-type != 'wsl'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache pip (cross-platform)
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          C:\Users\runneradmin\AppData\Local\pip\Cache
        key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ inputs.python-version }}-${{ hashFiles(inputs.requirements-file || '**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ inputs.python-version }}-

    # Unix/macOS setup
    - name: Setup venv (Unix/macOS)
      if: runner.os != 'Windows'
      id: setup-unix
      shell: bash
      env:
        INPUT_VENV_PATH: ${{ inputs.venv-path }}
        INPUT_REQUIREMENTS_FILE: ${{ inputs.requirements-file }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        chmod +x "$ACTION_PATH/scripts/setup-venv.sh"
        "$ACTION_PATH/scripts/setup-venv.sh" \
          "$INPUT_VENV_PATH" \
          "$INPUT_REQUIREMENTS_FILE"
        echo "venv-path=$INPUT_VENV_PATH" >> $GITHUB_OUTPUT
        echo "python-path=$INPUT_VENV_PATH/bin/python" >> $GITHUB_OUTPUT

    # Windows cmd setup
    - name: Setup venv (Windows cmd)
      if: runner.os == 'Windows' && (inputs.shell-type == 'cmd' || inputs.shell-type == '')
      id: setup-win-cmd
      shell: cmd
      env:
        INPUT_VENV_PATH: ${{ inputs.venv-path }}
        INPUT_REQUIREMENTS_FILE: ${{ inputs.requirements-file }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        call "%ACTION_PATH%\scripts\setup-venv.cmd" ^
          "%INPUT_VENV_PATH%" ^
          "%INPUT_REQUIREMENTS_FILE%"
        echo venv-path=%INPUT_VENV_PATH%>> %GITHUB_OUTPUT%
        echo python-path=%INPUT_VENV_PATH%\Scripts\python.exe>> %GITHUB_OUTPUT%

    # Windows PowerShell setup
    - name: Setup venv (Windows pwsh)
      if: runner.os == 'Windows' && inputs.shell-type == 'pwsh'
      id: setup-win-pwsh
      shell: pwsh
      env:
        INPUT_VENV_PATH: ${{ inputs.venv-path }}
        INPUT_REQUIREMENTS_FILE: ${{ inputs.requirements-file }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        & "$env:ACTION_PATH\scripts\setup-venv.ps1" `
          -VenvPath "$env:INPUT_VENV_PATH" `
          -RequirementsFile "$env:INPUT_REQUIREMENTS_FILE"
        Write-Output "venv-path=$env:INPUT_VENV_PATH" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        Write-Output "python-path=$env:INPUT_VENV_PATH\Scripts\python.exe" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    # Windows WSL setup
    - name: Setup venv (Windows WSL)
      if: runner.os == 'Windows' && inputs.shell-type == 'wsl'
      id: setup-win-wsl
      shell: cmd
      env:
        INPUT_VENV_PATH: ${{ inputs.venv-path }}
        INPUT_REQUIREMENTS_FILE: ${{ inputs.requirements-file }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        rem Convert script and venv paths to WSL paths
        for /f "delims=" %%S in ('wsl wslpath -u "%ACTION_PATH%\scripts\setup-venv.sh"') do set "SCRIPT=%%S"
        for /f "delims=" %%W in ('wsl wslpath -u "%CD%"') do set "WPATH=%%W"

        rem Run setup script in WSL
        wsl bash -lc "chmod +x '%SCRIPT%' && '%SCRIPT%' '%WPATH%/%INPUT_VENV_PATH%' '%INPUT_REQUIREMENTS_FILE%'"

        rem Output paths (Windows-style for host consumption)
        echo venv-path=%INPUT_VENV_PATH%>> %GITHUB_OUTPUT%
        echo python-path=%INPUT_VENV_PATH%/bin/python>> %GITHUB_OUTPUT%
