name: "static-checks"
description: "Run static analysis checks (flake8, black, mypy, etc.) using shared scripts. Supports bash, cmd, pwsh."

inputs:
  no-security:
    description: "If 'true', skip security checks (bandit, semgrep, pip-audit)"
    required: false
    default: "false"
  windows-shell:
    description: "On Windows, which shell to use: cmd | pwsh | wsl"
    required: false
    default: "cmd"

runs:
  using: "composite"
  steps:
    - name: Static checks (bash)
      if: runner.os != 'Windows'
      shell: bash
      run: ./scripts/ci/static-checks.sh ${{ inputs.no-security == 'true' && '--no-security' || '' }}

    - name: Static checks (cmd)
      if: runner.os == 'Windows' && (inputs.windows-shell == 'cmd')
      shell: cmd
      run: scripts\ci\static-checks.cmd ${{ inputs.no-security == 'true' && '--no-security' || '' }}

    - name: Static checks (pwsh)
      if: runner.os == 'Windows' && (inputs.windows-shell == 'pwsh')
      shell: pwsh
      run: ./scripts/ci/static-checks.ps1 ${{ inputs.no-security == 'true' && '--no-security' || '' }}
