name: "run-tests"
description: "Set up a Python version, cache pip, install deps and run tests producing coverage. Supports Windows cmd, PowerShell, or running inside WSL. Optional upload of coverage artifact."

inputs:
  python-version:
    description: "Python version (e.g. '3.13')"
    required: true
  requirements-file:
    description: "Requirements file to install (default: requirements-dev.txt)"
    required: false
    default: "requirements-dev.txt"
  test-args:
    description: "Additional pytest args (default: tests/ -v --maxfail=1 -n auto)"
    required: false
    default: "tests/ -v --maxfail=1 -n auto"
  coverage-file:
    description: "Optional coverage filename (default: coverage-<version>.xml)"
    required: false
    default: ""
  windows-shell:
    description: "On Windows, which shell to use: cmd | pwsh | wsl"
    required: false
    default: "cmd"
  upload-coverage:
    description: "If 'true', upload the produced coverage xml as an artifact from this step (default: false)"
    required: false
    default: "false"

outputs:
  coverage-file:
    description: "Path to coverage xml produced."

runs:
  using: "composite"
  steps:
    # Setup WSL with Ubuntu (required for Windows WSL shell) - must come before setup-venv
    - name: Setup WSL
      if: runner.os == 'Windows' && (inputs.windows-shell == 'wsl')
      uses: Vampire/setup-wsl@v5
      with:
        distribution: Ubuntu-24.04
        additional-packages: python3 python3-pip python3-venv

    # Copy workspace to WSL ext4 filesystem for faster I/O
    - name: Copy workspace to WSL ext4 filesystem
      if: runner.os == 'Windows' && (inputs.windows-shell == 'wsl')
      shell: cmd
      run: |
        rem Convert Windows path to WSL path
        for /f "delims=" %%P in ('wsl wslpath -u "%CD%"') do set "WPATH=%%P"
        rem Remove existing workspace and create fresh copy
        wsl bash -lc "rm -rf ~/gitspaces"
        wsl bash -lc "mkdir -p ~/gitspaces"
        rem Copy files (ignore hidden file copy errors for .git internals)
        wsl bash -lc "cp -r '%WPATH%'/* ~/gitspaces/"
        wsl bash -lc "cp -r '%WPATH%'/.[!.]* ~/gitspaces/ 2>/dev/null || true"

    # Use setup-venv action to create venv and install dependencies
    - name: Setup venv and install dependencies
      id: venv
      uses: ./.github/actions/setup-venv
      with:
        python-version: ${{ inputs.python-version }}
        venv-path: .venv
        requirements-file: ${{ inputs.requirements-file }}
        shell-type: ${{ runner.os == 'Windows' && inputs.windows-shell || '' }}

    # Unix / macOS path
    - name: Run tests on Unix/macOS
      if: runner.os != 'Windows'
      id: run_unix
      shell: bash
      env:
        INPUT_COVERAGE_FILE: ${{ inputs.coverage-file }}
        INPUT_PYTHON_VERSION: ${{ inputs.python-version }}
        INPUT_TEST_ARGS: ${{ inputs.test-args }}
        VENV_PATH: ${{ steps.venv.outputs.venv-path }}
      run: |
        COVERAGE_FILE="$INPUT_COVERAGE_FILE"
        if [ -z "$COVERAGE_FILE" ]; then
          COVERAGE_FILE="coverage-$INPUT_PYTHON_VERSION.xml"
        fi
        source "$VENV_PATH/bin/activate"
        python -m pytest $INPUT_TEST_ARGS --cov=src/gitspaces --cov-report=xml:$COVERAGE_FILE --cov-report=term
        echo "coverage-file=$COVERAGE_FILE" >> $GITHUB_OUTPUT

    # Windows: native cmd.exe
    - name: Run tests on Windows (cmd)
      if: runner.os == 'Windows' && (inputs.windows-shell == 'cmd')
      id: run_win_cmd
      shell: cmd
      env:
        INPUT_COVERAGE_FILE: ${{ inputs.coverage-file }}
        INPUT_PYTHON_VERSION: ${{ inputs.python-version }}
        INPUT_TEST_ARGS: ${{ inputs.test-args }}
        VENV_PATH: ${{ steps.venv.outputs.venv-path }}
      run: |
        set "COVERAGE_FILE=%INPUT_COVERAGE_FILE%"
        if "%COVERAGE_FILE%"=="" set "COVERAGE_FILE=coverage-%INPUT_PYTHON_VERSION%.xml"
        call "%VENV_PATH%\Scripts\activate.bat"
        python -m pytest %INPUT_TEST_ARGS% --cov=src/gitspaces --cov-report=xml:%COVERAGE_FILE% --cov-report=term
        echo coverage-file=%COVERAGE_FILE%>> %GITHUB_OUTPUT%

    # Windows: PowerShell
    - name: Run tests on Windows (PowerShell)
      if: runner.os == 'Windows' && (inputs.windows-shell == 'pwsh')
      id: run_win_pwsh
      shell: pwsh
      env:
        INPUT_COVERAGE_FILE: ${{ inputs.coverage-file }}
        INPUT_PYTHON_VERSION: ${{ inputs.python-version }}
        INPUT_TEST_ARGS: ${{ inputs.test-args }}
        VENV_PATH: ${{ steps.venv.outputs.venv-path }}
      run: |
        $coverage = $env:INPUT_COVERAGE_FILE
        if ([string]::IsNullOrEmpty($coverage)) { $coverage = "coverage-$env:INPUT_PYTHON_VERSION.xml" }
        $testArgs = $env:INPUT_TEST_ARGS
        & "$env:VENV_PATH\Scripts\Activate.ps1"
        Invoke-Expression "python -m pytest $testArgs --cov=src/gitspaces --cov-report=xml:$coverage --cov-report=term"
        Write-Output ("coverage-file=$coverage") | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    # Windows: run inside WSL (invoked via wsl.exe). Uses WSL ext4 filesystem for faster I/O.
    - name: Run tests on Windows (WSL)
      if: runner.os == 'Windows' && (inputs.windows-shell == 'wsl')
      id: run_win_wsl
      shell: cmd
      env:
        INPUT_COVERAGE_FILE: ${{ inputs.coverage-file }}
        INPUT_PYTHON_VERSION: ${{ inputs.python-version }}
        INPUT_TEST_ARGS: ${{ inputs.test-args }}
        VENV_PATH: ${{ steps.venv.outputs.venv-path }}
      run: |
        rem Determine coverage filename
        set "COVERAGE_FILE=%INPUT_COVERAGE_FILE%"
        if "%COVERAGE_FILE%"=="" set "COVERAGE_FILE=coverage-%INPUT_PYTHON_VERSION%.xml"

        rem Run pytest inside WSL using ext4 filesystem path (~/gitspaces)
        wsl bash -lc "cd ~/gitspaces && source '%VENV_PATH%/bin/activate' && python -m pytest %INPUT_TEST_ARGS% --cov=src/gitspaces --cov-report=xml:%COVERAGE_FILE% --cov-report=term"

        rem Export coverage-file to GITHUB_OUTPUT for workflow consumption
        echo coverage-file=%COVERAGE_FILE%>> %GITHUB_OUTPUT%

    # Copy coverage file back from WSL to Windows host for artifact upload
    - name: Copy coverage from WSL to host
      if: runner.os == 'Windows' && (inputs.windows-shell == 'wsl')
      shell: cmd
      env:
        INPUT_COVERAGE_FILE: ${{ inputs.coverage-file }}
        INPUT_PYTHON_VERSION: ${{ inputs.python-version }}
      run: |
        set "COVERAGE_FILE=%INPUT_COVERAGE_FILE%"
        if "%COVERAGE_FILE%"=="" set "COVERAGE_FILE=coverage-%INPUT_PYTHON_VERSION%.xml"
        for /f "delims=" %%P in ('wsl wslpath -u "%CD%"') do set "WPATH=%%P"
        wsl bash -lc "cp ~/gitspaces/%COVERAGE_FILE% '%WPATH%/%COVERAGE_FILE%'"

    # Optional: upload coverage artifact from inside the composite action if requested
    - name: Upload coverage artifact (if requested)
      if: ${{ inputs.upload-coverage == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ inputs.python-version }}-${{ runner.os }}
        # try explicit coverage-file input first, otherwise default filename
        path: |
          ${{ inputs.coverage-file }}
          coverage-${{ inputs.python-version }}.xml
