name: "python-tests: WSL steps"
description: "Reusable WSL-specific steps for tests: setup WSL, install Python, install deps, lint, test and conditional coverage upload."
inputs:
  python-version:
    description: "Python version to install/run (e.g. 3.13)"
    required: true
  os:
    description: "OS name from the matrix (e.g. ubuntu-latest) - used for conditional uploads"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up WSL
      uses: Vampire/setup-wsl@v3
      with:
        distribution: Ubuntu-22.04
        use-cache: false

    - name: Set up Python (WSL)
      shell: wsl-bash {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get update
        # Install Python and venv module (distutils not available in Python 3.12+)
        sudo apt-get install -y python${{ inputs.python-version }} python${{ inputs.python-version }}-venv
        python${{ inputs.python-version }} --version

    - name: Create virtual environment (WSL)
      shell: wsl-bash {0}
      run: |
        # Create a virtual environment which includes pip via ensurepip
        python${{ inputs.python-version }} -m venv .venv
        # Verify the venv was created and pip is available
        .venv/bin/python --version
        .venv/bin/pip --version

    - name: Install dependencies (WSL)
      shell: wsl-bash {0}
      run: |
        .venv/bin/pip install --upgrade pip setuptools wheel
        .venv/bin/pip install -e .
        .venv/bin/pip install -r requirements-dev.txt

    - name: Lint (WSL)
      shell: wsl-bash {0}
      run: |
        .venv/bin/python -m flake8 src/gitspaces --count --select=E9,F63,F7,F82 --show-source --statistics
        .venv/bin/python -m flake8 src/gitspaces --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests (WSL)
      shell: wsl-bash {0}
      run: |
        .venv/bin/python -m pytest tests/ -v --cov=src/gitspaces --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov (WSL)
      if: ${{ inputs.os == 'ubuntu-latest' && inputs.python-version == '3.11' }}
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
